wordpress_names = {
	'Alex King': 'alexkingorg',
	'Andrew Nacin': 'nacin',
	'Andrew Ozz': 'azaozz',
	'Daryl Koopersmith': 'koopersmith',
	'Dion Hulse': 'dd32',
	'Dominik Schilling (ocean90)': 'ocean90',
	'Donncha O Caoimh': 'donncha',
	'Dougal Campbell': 'dougal',
	'Drew Jaynes (DrewAPicture)': 'drewapicture',
	'DrewAPicture': 'drewapicture',
	'Drew Jaynes': 'drewapicture',
	'Helen Hou-Sandi': 'helen',
	'Ian Stewart': 'iandstewart',
	'John Blackbourn': 'johnbillion',
	'Jon Cave': 'duck_',
	'Joseph Scott': 'josephscott',
	'Lance Willett': 'lancewillett',
	'Mark Jaquith': 'markjaquith',
	'Matt Mullenweg': 'matt',
	'Matt Thomas': 'iammattthomas',
	'Michael Adams (mdawa': 'mdawaffe',
	'Mike Little': 'mikelittle',
	'Nikolay Bachiyski': 'nbachiyski',
	'Pete Mall': 'petemall',
	'Peter Westwood': 'westi',
	'Ron Rennick': 'wpmuguru',
	'Ryan Boren': 'ryan',
	'Scott Taylor': 'wonderboymusic',
	'Sergey Biryukov': 'sergeybiryukov',
}
